apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-deployment
  namespace: qa
  annotations:
      circleci.com/project-id: 65e67862-c875-4a84-82d5-3f22f0702fc5
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-container
        image: gelesko/my-k8s-app:qa
        ports:
        - containerPort: 3000
